### ISSUE TITLE
Chatbox 

### ISSUE THREAD

**Issue by Hexeption** [Zerthox/ClearVision#47]
Discord has updated the chat box so its not matching with all the other elements 
![](https://i.gyazo.com/774a3958bf68a392e631fdc5d2c55f5e.jpg)

**Comment by OmgDani** [comment]
```css
.channel-text-area-default [class*="inner-"],  /* The chat bar */
.channel-text-area-default [class*="autocomplete-"], /* Auto complete wrapper */
.channel-text-area-default [class*="autocompleteInner-"], /* Auto complete container */
.channel-text-area-default [class*="selectorSelected-"] { /* Selected item in auto complete */
    background-color: rgba(0,0,0,.6); }
.channel-text-area-default [class*="textArea-"], /* Text in chat bar */
.channel-text-area-default [class*="selector-"] [class*="marginLeft8-"] { /* User names in auto complete */
    color: white; }

.theme-dark .inner-3if5cm {
    background: rgba(0,0,0,0.6);
}
```

Thanks to tehbasshunter for this fix
