### ISSUE TITLE
Is there a way to make this lighter?

### ISSUE THREAD

**Issue by Rocket-PropelledWeeb** [Zerthox/ClearVision#65]
The main part of the window used to be a lot brighter, about the same brightness as the channel rack, now it's too dark for my liking. How do I lighten it?
![help](https://user-images.githubusercontent.com/33541158/32648437-88226104-c5aa-11e7-87ca-d6f76494a080.jpg)
Edit: In the screenshot it looks a lot brighter. I really don't know why.

**Comment by OmgDani** [comment]
```css
.content .flex-spacer, DIV[class*="flex-"][class*="title-"] {
  background-color: rgba(0, 0, 0, 0.35)!important;
}

```
