### ISSUE TITLE
Code blocks have bad wrapping

### ISSUE THREAD

**Issue by shiyah** [Zerthox/ClearVision#67]
![image](https://user-images.githubusercontent.com/17354971/33970758-bdd0b076-e06c-11e7-831c-993198d545a9.png)
When lines are too long, the message will not wrap except on newlines.
This is because messages inherit `white-space: pre` from the discord stylesheet.

This can be changed to be somewhat more functional by changing the rule to `white-space: pre-wrap`
![image](https://user-images.githubusercontent.com/17354971/33970887-70db09a0-e06d-11e7-92e0-fdd7bc98a945.png)

The addition will end up being
```css
.message-group .comment .markup pre {
    white-space: pre-wrap;
}
```
